version: "3"

services:

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bzklink
    ports:
      - 3306:3306
    volumes:
       - bzklink:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 9090:80

volumes:
  bzklink: